### ISSUE TITLE
[Important] Modified build detected

### ISSUE THREAD

**Issue by wxnnvs** [wxnnvs/seb-win-bypass#2]
**Describe the Bug**
After being AFK for a while SEB locks itself saying you're using a modified SEB version.
This happens also, when crashing and restarting an exam.

**Steps to Reproduce**
1. Open an exam
2. Wait for some time
3. Locked screen

Or 

1. Open exam
2. Crash it using the menu
4. Rejoin
5. Locked screen

**Expected Behavior**
SEB shouldn't be able to detect a modified build.

**Screenshots**
![IMG-20240911-WA0012.jpg](https://github.com/user-attachments/assets/2ff4d037-4688-4b51-9125-4064bcbf5cef)

**Version Information**
 - OS: Windows 11 Education
 - SEB-Version: 3.7.1  (from the website)

**Additional Context**
Some people have encountered it right after installing.
I personally never had this issue, gonna try to reproduce soon.

**Comment by Specki3000** [comment]
I had the same problem... Many thanks for your time! I don't have much idea about C# but maybe I can help you somehow

**Comment by wxnnvs** [comment]
> I had the same problem... Many thanks for your time! I don't have much idea about C# but maybe I can help you somehow

Try reading this:
https://wxnnvs.ftp.sh/un-seb/#docs

Btw, try to always move your mouse and randomly click. Being AFK for too long locks you out

**Comment by Specki3000** [comment]
You think it won't happen just by moving the mouse? I will try it the next time.

**Comment by wxnnvs** [comment]
> You think it won't happen just by moving the mouse? I will try it the next time.

I tested it in a real test, it didn't lock me out if i just clicked randomly and moved my mouse enough.

**Comment by wxnnvs** [comment]
@Specki3000 later today, i will release a fix for this, you can check out the latest commit in the 3.7.1 branch

**Comment by wxnnvs** [comment]
@Specki3000 fixed in latest release

**Comment by Specki3000** [comment]
Hey wxnnvs, thank you very much for your work! I will try it as soon as possible and give you feed back👍

**Comment by wxnnvs** [comment]
No problem at all!
I hope it works for you
