### ISSUE TITLE
Some strange problems with opening web pages

### ISSUE THREAD

**Issue by T-ong-T-ie** [wxnnvs/seb-win-bypass#3]
I cannot open any URL I enter, and it always displays 404, but the official website of SEB can be opened normally.

**Comment by T-ong-T-ie** [comment]
I think I know the reason, because SEB is linked to the university's server, but the university's server cannot resolve websites outside the university, so it shows 404.

**Comment by wxnnvs** [comment]
Hey, im sorry that im reacting so late.
Try putting 'https://' in front of the url
If that doesn't work it is indeed your university

**Comment by wxnnvs** [comment]
You could also test this on your home wifi using a [demo exam](https://safeexambrowser.org/exams)
